In [1]:
import pandas as pd

In [2]:
dfusers=pd.read_csv("user+data.csv")
dfusers

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

Importamos las librerias correspondientes

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix

Seleccionamos los datos que van a ir en X, y de la funcion

In [4]:
X=dfusers.iloc[ : , 2:4].values
y=dfusers.iloc[: ,4]. values
print(X)
print(y)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

Seleccion de datos de entrenamiento y de prueba

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.25, random_state=9)

In [11]:
#do the training with sklearn
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
#se usa fit_transform para escalar los datos de la serie X_train y X_test
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.fit_transform(X_test)


In [12]:
print(X_train)
print(X_test)
#Verificamos el escalado de los conjuntos de datos con valores con una media de 0 y desviacion estandar de 1 para que los 
#pueda procesar el algoritmo de apremdizaje automatico

[[-0.61696196 -1.63544915]
 [-0.23729306  0.78219697]
 [ 0.71187919 -1.42906472]
 [-0.90171364  0.54632906]
 [-0.04745861  2.16792097]
 [-0.23729306 -0.16127469]
 [ 0.99663086 -1.04577936]
 [-0.99663086 -0.36765911]
 [ 0.23729306  0.04510974]
 [ 0.99663086  2.0794705 ]
 [-1.47121698 -0.22024166]
 [ 1.09154808 -1.25216379]
 [-0.99663086 -1.4880317 ]
 [-0.99663086  0.57581255]
 [ 0.23729306 -0.16127469]
 [-1.09154808 -1.13422983]
 [ 1.56613421 -1.31113077]
 [-1.09154808  0.31046114]
 [ 2.04072033  0.1630437 ]
 [-1.75596866 -0.01385724]
 [ 1.94580311  0.72322999]
 [ 0.42712751  0.98858139]
 [-0.90171364 -0.33817562]
 [ 2.13563756  0.36942812]
 [-0.23729306 -1.34061426]
 [-0.14237584 -0.48559307]
 [-0.42712751  2.31533841]
 [ 2.04072033  0.51684557]
 [ 1.47121698  0.33994463]
 [ 0.04745861 -0.27920864]
 [-1.09154808  1.40135024]
 [ 0.23729306 -0.3971426 ]
 [-0.33221029 -0.80991145]
 [-0.23729306 -0.60352703]
 [ 0.52204474  1.84360258]
 [-0.61696196  0.10407672]
 [-0.14237584 -1.10474634]
 

In [18]:
from sklearn.neighbors import KNeighborsClassifier
Classifier=KNeighborsClassifier(n_neighbors=5, metric="minkowski",p=2)
Classifier.fit(X_train,y_train)


KNeighborsClassifier()

In [20]:
#ponemos el modelo a predecir los valores de X_test
y_pred=Classifier.predict(X_test)
#Creamos una matriz de confusion para probar el error de la matriz de prediccion vs la matriz de prueba
cm=confusion_matrix(y_pred,y_test)
print(cm)

[[58  5]
 [ 2 35]]


Esta matriz de confusion dice que 58 valores verdaderos se predicen correctamente verdaderos, 
5 valores falsos se predicen incorrectamente como verdaderos
2 valores verdaderos se predicen incorrectamente como falsos 
35 valores falsos se predicen correctamente como falsos

Si se suman los resultados correctos con los resultados incorrectos nos da una precision de 99.92%